language: generic

services:
  - docker

env:
  matrix:
    - DISTRIBUTIONS=debian.wheezy
    - DISTRIBUTIONS=debian.jessie
    - DISTRIBUTIONS=debian.stretch
    - DISTRIBUTIONS=centos.7
    - DISTRIBUTIONS=ubuntu.xenial

script:
  - make build
  - make test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/430e0a92ad6370b7b805
    on_success: change
    on_failure: always
    on_start: never
