language: generic

branches:
  only:
    - master

services:
  - docker

env:
  matrix:
    - DISTRIBUTIONS=debian.wheezy
    - DISTRIBUTIONS=debian.jessie
    - DISTRIBUTIONS=debian.stretch
    - DISTRIBUTIONS=debian.buster
    - DISTRIBUTIONS=centos.7
    - DISTRIBUTIONS=ubuntu.xenial

script:
  - make build
  - make test

jobs:
  include:
    - stage: release
      script:
        - gem install chandler -v 0.9.0
        - chandler push `perl -lne '/^## \[(?!Unreleased)([\w.-]+)\] - [\w-]+$/ && print $1;' CHANGELOG.md | head -1`

