FROM centos:7

MAINTAINER Manala <contact@manala.io>

USER root

# Packages
RUN yum clean all && yum -y update && \
    yum -y install \
# System
      sudo \
# Shell
      bash bash-completion \
# Tools
      less vim wget curl make git

# Sudo
RUN sed -i -e '/secure_path/ s[=.*[&:/usr/local/bin[' /etc/sudoers

# Su exec
ENV SU_EXEC_VERSION="0.2"
RUN yum -y install gcc && \
    curl -L https://github.com/ncopa/su-exec/archive/v${SU_EXEC_VERSION}.tar.gz \
      | tar zxfv - -C /tmp --strip-components=1 && \
    make --directory /tmp  && \
    mv /tmp/su-exec /usr/local/bin && \
    yum -y remove gcc

# Dumb init
ENV DUMB_INIT_VERSION="1.2.0"
RUN curl -L https://github.com/Yelp/dumb-init/releases/download/v${DUMB_INIT_VERSION}/dumb-init_${DUMB_INIT_VERSION}_amd64 -o /usr/local/bin/dumb-init && \
    chmod +x /usr/local/bin/dumb-init

# Goss
ENV GOSS_VERSION="0.3.5"
RUN curl -fsSL https://goss.rocks/install | GOSS_VER=v${GOSS_VERSION} sh

# Entrypoint
COPY entrypoint.sh /usr/local/bin/
ENTRYPOINT ["entrypoint.sh"]

# Shell
CMD ["/bin/bash"]

# Working directory
WORKDIR /srv

########
# User #
########

ARG USER_ID
ARG GROUP_ID

ENV USER_DEFAULT="manala" \
    USER_ID="${USER_ID:-1000}" \
    USER_SUDO="1" \
    GROUP_DEFAULT="manala" \
    GROUP_ID="${GROUP_ID:-1000}"

RUN groupadd -g ${GROUP_ID} ${GROUP_DEFAULT} && \
    useradd --shell /bin/bash --uid ${USER_ID} --gid ${GROUP_DEFAULT} ${USER_DEFAULT}

##########
# Custom #
##########

# Pip packages
ENV JINJA2_VERSION="2.8" \
    ANSIBLE_VERSION="2.3.2.0" \
    ANSIBLE_LINT_VERSION="3.4.16"
RUN yum -y install \
      python python-setuptools python-devel gcc && \
    easy_install pip && \
    pip install --upgrade setuptools && \
    pip --no-cache-dir --disable-pip-version-check install \
      Jinja2==${JINJA2_VERSION} \
      ansible==${ANSIBLE_VERSION} \
      ansible-lint==${ANSIBLE_LINT_VERSION} && \
    yum -y remove python-devel gcc

# Ansible hosts
COPY ansible/hosts.centos.7 /etc/ansible/hosts

# Clean
RUN yum -y autoremove && \
    yum clean all
