#!/bin/bash

# Check docker tag has flavour (like in "1.2.3.4-foo", where "foo" is the flavour)
# or not (like in "1.2.3.4")
if [[ "$DOCKER_TAG" == *-* ]]
then
  FLAVOUR=${DOCKER_TAG#*-}
  VERSION=${DOCKER_TAG%-*}
else
  VERSION=${DOCKER_TAG}
fi

VERSION_PATCH=${VERSION%.*}
VERSION_MINOR=${VERSION_PATCH%.*}
VERSION_MAJOR=${VERSION_MINOR%.*}

# Version - Patch
# 1.2.3.4     -> 1.2.3
# 1.2.3.4-foo -> 1.2.3-foo
docker tag $IMAGE_NAME $DOCKER_REPO:$VERSION_PATCH${FLAVOUR:+-${FLAVOUR}}
docker push $DOCKER_REPO:$VERSION_PATCH${FLAVOUR:+-${FLAVOUR}}

# Version - Minor
# 1.2.3.4     -> 1.2
# 1.2.3.4-foo -> 1.2-foo
docker tag $IMAGE_NAME $DOCKER_REPO:$VERSION_MINOR${FLAVOUR:+-${FLAVOUR}}
docker push $DOCKER_REPO:$VERSION_MINOR${FLAVOUR:+-${FLAVOUR}}

# Version - Major
# 1.2.3.4     -> 1
# 1.2.3.4-foo -> 1-foo
docker tag $IMAGE_NAME $DOCKER_REPO:$VERSION_MAJOR${FLAVOUR:+-${FLAVOUR}}
docker push $DOCKER_REPO:$VERSION_MAJOR${FLAVOUR:+-${FLAVOUR}}

# Flavour or Latest
# 1.2.3.4     -> latest
# 1.2.3.4-foo -> foo
docker tag $IMAGE_NAME $DOCKER_REPO:${FLAVOUR:-latest}
docker push $DOCKER_REPO:${FLAVOUR:-latest}
