# Server configuration
server:
    hostname: openl10n.domain.tld
    use_ssl:  true
    username: openl10n
    password: PaSsWoRd

# Project identifier
project: your_project

# Path to the translation files
files:
  -
    pattern: src/app/Resources/translations/*.<locale>.*
    options:
      # Options when pushing (importing) translation files:
      # - reviewed  = Mark directly all translations as approved
      # - erase     = Replace existing translations by the ones in the files
      # - clean     = Delete translations which are not present in the files anymore
      push: []

      # Options when pulling (exporting) translation files:
      # - fallback_locale = If translation does not exist in a locale (eg. French), dump the default (eg. English) translation
      # - fallback_key    = If the default translation (eg. English) does not exist, use the key as a valid translation
      # - reviewed        = Dump only reviewed translations (and ignore the rest)
      pull: [fallback_locale]
