# List of splits.
splits:
  - prefix: build-debian
    target: git@github.com:manala/docker-image-build-debian.git
  - prefix: client-openstack
    target: git@github.com:manala/docker-image-client-openstack.git
  - prefix: lint-css
    target: git@github.com:manala/docker-image-lint-css.git
  - prefix: lint-js
    target: git@github.com:manala/docker-image-lint-js.git
  - prefix: lint-php
    target: git@github.com:manala/docker-image-lint-php.git
  - prefix: test-js
    target: git@github.com:manala/docker-image-test-js.git

# List of references to split (defined as regexp)
origins:
  - ^master$
