# Used to speed up the split over time by reusing git's objects
cache_url: "./.gitsplit"

# List of splits.
splits:
  # Deprecated
  #- prefix: ansible-debian
  #  target: git@github.com:manala/docker-image-ansible-debian.git
  - prefix: build-debian
    target: git@github.com:manala/docker-image-build-debian.git
  - prefix: client-openstack
    target: git@github.com:manala/docker-image-client-openstack.git
  # Deprecated
  #- prefix: deploy
  #  target: git@github.com:manala/docker-image-deploy.git
  - prefix: hugo
    target: git@github.com:manala/docker-image-hugo.git
  # Deprecated
  #- prefix: lint-css
  #  target: git@github.com:manala/docker-image-lint-css.git
  # Deprecated
  #- prefix: lint-js
  #  target: git@github.com:manala/docker-image-lint-js.git
  # Deprecated
  #- prefix: lint-php
  #  target: git@github.com:manala/docker-image-lint-php.git
  - prefix: openl10n-cli
    target: git@github.com:manala/docker-image-openl10n-cli.git
  - prefix: php-cs-fixer
    target: git@github.com:manala/docker-image-php-cs-fixer.git
  - prefix: security-checker
    target: git@github.com:manala/docker-image-security-checker.git
  - prefix: test-ansible
    target: git@github.com:manala/docker-image-test-ansible.git
  # Deprecated
  #- prefix: test-js
  #  target: git@github.com:manala/docker-image-test-js.git
  # Deprecated
  #- prefix: test-php
  #  target: git@github.com:manala/docker-image-test-php.git

# List of references to split (defined as regexp)
origins:
  - ^master$
