language: generic

sudo: required

services:
  - docker

before_install:
  - make build

script:
  - make test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/430e0a92ad6370b7b805
    on_success: change
    on_failure: always
    on_start: never
