language: generic

branches:
  only:
    - master

services:
  - docker

before_install:
  # Install goss
  - curl -L https://goss.rocks/install | sudo sh

script:
  # Register Qemu in the kernel of the host.
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - make build
  - make test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/430e0a92ad6370b7b805
    on_success: change
    on_failure: always
    on_start: never
