############
# Packages #
############

package:
  su-exec:
    installed: true
  bash:
    installed: true
  curl:
    installed: true
  make:
    installed: true
  git:
    installed: true
  # Custom
  rsync:
    installed: true
  openssh-client:
    installed: true

############
# Commands #
############

command:
  dumb-init --version:
    exit-status: 0
    stderr:
      - dumb-init v{{ .Env.DUMB_INIT_VERSION }}

#########
# Files #
#########

file:
  # Custom
  /etc/ssh/ssh_config:
    exists:   true
    filetype: file
    contains:
      - /StrictHostKeyChecking\s+no/
      - /ForwardAgent\s+yes/
      - /UserKnownHostsFile\s+/dev/null/
      - /LogLevel\s+ERROR/

##########
# Groups #
##########

group:
  {{ .Env.GROUP_DEFAULT }}:
    exists: true
    gid:    {{ .Env.GROUP_ID }}

#########
# Users #
#########

user:
  {{ .Env.USER_DEFAULT }}:
    exists: true
    uid:    {{ .Env.USER_ID }}
    groups:
      - {{ .Env.GROUP_DEFAULT }}
    home:  /home/{{ .Env.USER_DEFAULT }}
    shell: /bin/bash
