language: generic

sudo: required

services:
  - docker

env:
  - DEBIAN_DISTRIBUTION=wheezy
  - DEBIAN_DISTRIBUTION=jessie
  - DEBIAN_DISTRIBUTION=stretch

script:
  - make build
  - make test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/430e0a92ad6370b7b805
    on_success: change
    on_failure: always
    on_start: never
