#!/bin/bash

VERSION=${SOURCE_BRANCH}
VERSION_MINOR=${VERSION%.*}
VERSION_MAJOR=${VERSION_MINOR%.*}

# Version - Minor
docker tag $IMAGE_NAME $DOCKER_REPO:$VERSION_MINOR
docker push $DOCKER_REPO:$VERSION_MINOR

# Version - Major
docker tag $IMAGE_NAME $DOCKER_REPO:$VERSION_MAJOR
docker push $DOCKER_REPO:$VERSION_MAJOR

# Latest
docker tag $IMAGE_NAME $DOCKER_REPO:latest
docker push $DOCKER_REPO:latest
