language: generic

branches:
  only:
    - master

services:
  - docker

env:
  matrix:
    - RELEASES=jessie
    - RELEASES=stretch
    - RELEASES=buster

script:
  - make build
  - make test

jobs:
  include:
    - stage: release
      script:
        - gem install chandler -v 0.9.0
        - chandler push `perl -lne '/^## \[(?!Unreleased)([\w.-]+)\] - [\w-]+$/ && print $1;' CHANGELOG.md | head -1`
